config/routes.rb
LadyBug::Application.routes.draw do

  devise_for :users do
    root to: "devise/sessions#new"
  end

  resources :users do
    match 'add_role' => 'users#add_role', via: :post
    match 'remove_role' => 'users#remove_role', via: :post
  end

  resources :projects do 
    resources :versions
    resources :issues do
      collection do
        match 'search' => 'issues#search', via: [:get, :post], as: :search
      end
      resources :notes
    end   
  end

  

end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :body, :issue_id, presence: true
 	belongs_to :issue
 	belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	before_filter :authenticate_user!

	def create
  		@note = Note.new(note_params)
  		@note.issue_id = params[:issue_id]
  		@note.user_id = current_user.id

 		@note.save

 		flash[:success]= "Note created!"

  		redirect_to project_issue_path(@note.issue.project, @note.issue)
	end

	def destroy
		@note = Note.find(params[:id])
		@note.destroy

		flash[:error]= "Note Deleted!"

		redirect_to project_issue_path(@note.issue.project, @note.issue)
	end


	private
	def note_params
  		params.require(:note).permit(:body)
	end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<legend>Post a Note:</legend>
<%=  form_for @note, url: project_issue_notes_path(@project,@issue) do |f| %>
  <p>
    <%= f.text_area :body ,class: "span12"%>
  </p>
  <p>
    <%= f.submit 'Save comment', class: "btn btn-mini btn-primary"  %>
  </p>
<% end %>

app/views/notes/_note.html.erb
<blockquote>
	<small>Created at <%= note.created_at%> by <%= User.find(note.user_id).email%></small>
  	<%= note.body %>
</blockquote>

<%= link_to(project_issue_note_path(note.issue.project, note.issue, note), method: :delete, data: {confirm: "Really delete the note?"}, class: "btn btn-danger btn-mini") do %>
  	<i class="icon-trash icon-white"></i>
<%end%></br>