config/routes.rb
LadyBug::Application.routes.draw do

  devise_for :users do
    root to: "devise/sessions#new"
  end

  resources :users do
    match 'add_role' => 'users#add_role', via: :post
    match 'remove_role' => 'users#remove_role', via: :post
  end

  resources :projects do 
    resources :versions
    resources :issues do
      collection do
        match 'search' => 'issues#search', via: [:get, :post], as: :search
      end
      resources :notes
    end   
  end

  

end

app/models/issue.rb
class Issue < ActiveRecord::Base

	has_many :notes
	belongs_to :project

	validates :title, :description, :product_version, presence: true
	validates_uniqueness_of :title, scope: :project_id

	SEVERITY = [:critical, :evolution, :minor, :cosmetic]
	IMPACT = [:specification, :design, :code, :unit_test, :integration, :validation]

	state_machine :initial => :new do
		state :new, value: 0
		state :reopened, value: 1
		state :analysed, value: 2
		state :assigned, value: 3
		state :corrected, value: 4
		state :reviewed, value: 5
		state :validated, value: 6
		state :closed, value: 7

		state :cancelled, value: -1


		event :analyse do
			transition [:new, :reopened] => :analysed
		end

		state :analysed do
			validates :analysis, :impact, presence: true
		end

		event :assign do
			transition :analysed => :assigned
		end

		state :assigned do 
			validates :target_version, presence: true
		end

		event :correct do
			transition :assigned => :corrected
		end

		state :corrected do
			validates :correction, presence: true
		end

		event :review do
			transition :corrected => :reviewed
		end

		state :reviewed do
			validates :review_ref, presence:true
		end

		event :validate do
			transition :reviewed => :validated
		end

		state :validated do
			validates :validation_ref, presence: true
		end


		event :close do
			transition :validated => :closed
		end

		event :reopen do
			transition [:closed, :cancelled] => :reopened
		end

		event :cancel do
			transition all - [:corrected,:reviewed,:validated,:closed]=> :cancelled
		end


  	end

  	def self.ransackable_attributes(auth_object = nil)
    	super - ['project_id']
  	end

	def next
	    Issue.where("id > ? and project_id = ?", self.id, self.project_id).first
	end

	def prev
    	Issue.where("id < ? and project_id = ?", self.id, self.project_id).last
	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

	before_filter :find_issue, except: [:index, :new, :create, :search]
	before_filter :define_note, only: [:show, :update]
	before_filter :define_project
	before_filter :authenticate_user!
	
	def index
		@issues = @project.issues
	end	

	def new
		@issue = Issue.new
	end

	def create
		@issue = Issue.new(issue_params)
		@issue.project_id = @project.id
		respond_to do |format|
			if @issue.save
				format.html {redirect_to project_issue_path(@issue.project, @issue), :flash => { :success => "Issue succesfully created." } }
				format.json {head :no_content}
			else
				format.html { render action: 'new'}
				format.json { render json: @issue.errors, status: :unprocessable_entity }
			end
		end
	end

	def show
		@productversion = Version.find(@issue.product_version)
		@targetversion = Version.find(@issue.target_version) if @issue.target_version
	end

	def search
		@search = @project.issues.search(params[:q])
		@project_issues = @search.result.page(params[:page]).per(25)
		@search.build_condition if @search.conditions.empty?
  		@search.build_sort if @search.sorts.empty?
		render 'projects/show'
	end

	def edit
	end

	def update
		case params[:commit]
		when "change issue state" then
			if @issue.fire_state_event(params[:issue][:state_event]) 
			  	respond_update_success
			else
			  	respond_update_error 'show'
			end
	    else
	    	if @issue.update(issue_params)
	      		@issue.fire_state_event(params[:issue][:state_event]) if params[:issue][:state_event]
		    	respond_update_success 
		  	else
		    	respond_update_error 'edit'
		  	end
		end
	end

	def destroy
		if @issue.state >= 4 #:corrected
			flash[:error]= "cannot deleted Issue '#{@issue.title}' because it is already corrected!"
			redirect_to project_issue_path(@project, @issue)
		else
			@issue.notes.destroy_all
			@issue.destroy

			flash[:error]= "Issue '#{@issue.title}' Deleted!"

			redirect_to project_issues_path(@project) 
		end
	end

	private
	def issue_params
		params.require(:issue).permit(:title, :description, 
			:analysis, :product_version, :target_version,
			:severity, :impact, :correction,
			:review_ref, :validation_ref)
	end

	def find_issue
		@issue = Issue.find(params[:id])
	end

	def define_note
		@note = Note.new
		@note.issue_id = @issue.id
	end

	def define_project
		@project = Project.find(params[:project_id])
	end

	def respond_update_success
	  respond_to do |format|
	    format.html { redirect_to project_issue_path(@project, @issue), :flash => { :success => 'Issue state was successfully updated.' }}
	    format.json { head :no_content }
	  end 
	end

	def respond_update_error path
	  respond_to do |format|
	  	format.html { render action: path }
	    format.json { render json: @issue.errors, status: :unprocessable_entity }
	  end
	end

end

app/helpers/issues_helper.rb
module IssuesHelper

	def state_label(state)
		case state
			when :new then "label label-important"
			when :analysed then "label label-info"
			when :assigned then "label label-warning"
			when :corrected then "label label-warning"
			when :reviewed then "label label-warning"
			when :validated then "label label-info"
			when :cancelled then "label"
			when :closed then "label label-inverse"
			when :reopened then "label label-important" 
		end
	end

	def progress(state)
		case state
			when :new then "10%"
			when :analysed then "30%"
			when :assigned then "50%"
			when :corrected then "60%"
			when :reviewed then "70%"
			when :validated then "80%"
			when :cancelled then "0%"
			when :closed then "100%"
			when :reopened then "10%" 
		end
	end

	def delivered_version(project)
		project.versions.select do |version|
			if version.delivered?
				version.number
			end
		end
	end

	def planned_version(project)
		project.versions.select do |version|
			version.number if version.planned? 
		end
	end

	def version_badge(state)
		case state
			when :planned then "badge badge-success"
			when :ongoing then "badge badge-important"
			when :delivered then "badge badge-inverse"
		end
	end

end

app/views/issues/_change_state.html.erb
<%= form_for [@project,@issue] do |f| %>
	<ul>
  		<% @issue.errors.full_messages.each do |error| %>
    		<li><span class="text-error"><%= error %></span></li>
  		<% end %>
  	</ul>
	<%= f.collection_select :state_event, @issue.state_transitions, :event, :human_to_name %> 
	<%= f.submit 'change issue state', class: "btn btn-success" %>
<% end %>

app/views/issues/_collapse.html.erb
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" href="#collapseOne">
        Description:
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">
        <%= @issue.description %>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" href="#collapseTwo">
        Analysis:
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
        <%= @issue.analysis %>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" href="#collapseThree">
        Correction:
      </a>
    </div>
    <div id="collapseThree" class="accordion-body collapse">
      <div class="accordion-inner">
        <%= @issue.correction %>
      </div>
    </div>
  </div>
</div>

app/views/issues/_edit_destroy.html.erb
<% if can? :update, issue%>
	<%= link_to 'edit', edit_project_issue_path(project,issue), class: "btn btn-info btn-mini" %> 
<% end%> 
<% if can? :destroy, issue%>
	<%= link_to(project_issue_path(project,issue), method: :delete, data: {confirm: "Really delete the issue?"}, class: "btn btn-danger btn-mini") do %>
	  	<i class="icon-trash icon-white"></i>
	<%end%>
<% end %>

app/views/issues/_form.html.erb
<%= form_for [@project, @issue] do |f| %>
	<ul>
  		<% @issue.errors.full_messages.each do |error| %>
    		<li><span class="text-error"><%= error %></span></li>
  		<% end %>
  </ul>
  <%= f.label :title, class: 'strong' %>
  <%= f.text_field :title, placeholder: "Enter issue title", class: "span12"%>
  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "Enter issue description", class: "span12", rows: '9' %>
  <%= f.label :product_version %>
  <%= f.collection_select :product_version, delivered_version(@project), :id, :number%>
  <%if @issue.state >= 2%>
    <%= f.label :target_version %>
    <%= f.collection_select :target_version, planned_version(@project), :id, :number%>
  <% end %>
  <%= f.label :severity %>
  <%= f.select :severity, Issue::SEVERITY %>
  <%= f.label :impact %>
  <%= f.select :impact, Issue::IMPACT%>
  <%= f.label :analysis %>
  <%= f.text_area :analysis, placeholder: "Enter an analysis", class: "span12" ,rows: "9" %>
  <%= f.label :correction %>
  <%= f.text_area :correction, placeholder: "Describe the correction and impacted files", class: "span12", rows: "9"%>
  <% if not @issue.review_ref.nil? %>
    <%= f.label 'Review reference'%>
    <%= f.text_field :review_ref%>
  <% end %>
  <% if not @issue.validation_ref.nil? %>
    <%= f.label 'validation reference'%>
    <%= f.text_field :review_ref%>
  <% end %>
<br />
  <%= f.submit 'Save', class: "btn btn-primary" %>
  <%= link_to 'Cancel', @project, class: "btn" %>
<% end %>

app/views/issues/_issue_nav.html.erb
<ul class="pager pager-inverse">
  <li><%= link_to "Issues list", project_path(@issue.project) %></li>
  <li class="previous"><%= link_to 'Previous', project_issue_path(@project, @issue.prev) %></li>
  <li class="next"><%= link_to 'Next', project_issue_path(@project, @issue.next)%></li>
</ul>

app/views/issues/_references.html.erb
<dl class="dl-horizontal ">
	<% if @issue.state >= 4 %>
		<% if @issue.review_ref.nil? or @issue.review_ref.empty?%>
			<%= form_for [@project,@issue] do |f| %>
				<%= f.text_field :review_ref%> 
				<%= f.submit 'add review reference', class: "btn btn-success" %>
		<% end %>
	<%else%>
		<dt>Review Reference:</dt>
		<dd><%= @issue.review_ref %></dd>
	<%end%>
<%end%>
<% if @issue.state >= 5 %>
	<% if @issue.validation_ref.nil? or @issue.validation_ref.empty?%>
		<%= form_for [@project,@issue] do |f| %>
			<%= f.text_field :validation_ref%> 
			<%= f.submit 'add validation reference', class: "btn btn-success" %>
		<% end %>
	<%else%>
		<dt>Validation Reference:</dt>
		<dd><%= @issue.validation_ref %></dd>
	<%end%>
<%end%>
</dl>

app/views/issues/_versions.html.erb
<dl class="dl-horizontal ">
	<dt>Product Version:</dt> 
	<dd>
		<span class='<%=version_badge(Version.find(@issue.product_version).state_name)%>'> <%=Version.find(@issue.product_version).number%> </span> 
	</dd>
	<dt>Target Version:</dt>
	<dd>
		<% if @issue.target_version %>
			<span class='<%=version_badge(Version.find(@issue.target_version).state_name)%>'> <%=Version.find(@issue.target_version).number%> </span>
		<% else %>
		    <span class='badge'>None</span>
		<%end%>
	</dd>
</dl>
<%if @issue.target_version.nil? or Version.find(@issue.target_version).delivered? %>
	<%= form_for [@project,@issue] do |f| %>
		<%= f.collection_select :target_version, planned_version(@project), :id, :number%> 
		<%= f.submit 'set target version', class: "btn btn-success" %>
	<% end %>
<% end %>

app/views/issues/edit.html.erb
<legend> Edit issue</legend>

<%= render partial: 'form' %>

<%= link_to(project_issue_path(@project,@issue), method: :delete, data: {confirm: "Really delete the issue?"}, class: "btn btn-danger btn-mini") do %>
  	<i class="icon-trash icon-white"></i>
<%end%>
<%= link_to 'Back to issue', project_issue_path(@project, @issue) %>

app/views/issues/index.html.erb
<h1> Issue list </h1>
<table class="table table-hover table-striped">
  <thead>
	<TR> 
 		<TH> Issue ID </TH> 
 		<TH> Title </TH> 
 		<TH> Actions </TH>
  </TR>
  </thead>
  	<% @issues.each do |issue| %>
  		<TR>
  			<TH> <%= link_to issue.id, project_issue_path(issue.project, issue) %> </TH>
  			<TH> <%= link_to issue.title, project_issue_path(issue.project, issue) %> </TH>
  			<TH> 
  				<div class="pull-right">
  				<%= link_to 'edit', edit_project_issue_path(issue.project, issue), class: "btn btn-info btn-mini" %>  
  				<%= link_to(project_issue_path(issue.project, issue), method: :delete, data: {confirm: "Really delete the issue?"}, class: "btn btn-danger btn-mini") do %>
  					<i class="icon-trash icon-white"></i>
				<%end%>
			</div>
  			</TH>
  		</TR>
  	<%end%>
</table>
<%= link_to "Create a New Issue", new_project_issue_path, class: "btn btn-primary"%>

app/views/issues/new.html.erb
<legend>Create a new issue</legend>

<%= render partial: 'form' %>

app/views/issues/show.html.erb
<%= render partial: 'issue_nav'%>

<div class='row-fluid'>
  <div class="span12">
    <legend>
      <span class='<%= state_label(@issue.state_name)%>'>
      <%= @issue.state_name %>
      </span>
      <%=@issue.title%>
    </legend>
    <div class="progress progress-info progress-striped">
      <div class="bar" style="width: <%= progress(@issue.state_name)%>"><%= progress(@issue.state_name)%> Done</div>
    </div>
    <div class='row-fluid'>
      <div class="span6">
        <%= render partial: 'change_state' %>
        <%= render partial: 'references' %>
      </div>
      <div class="span6">
        <%= render partial: 'versions'%>
        <dl class="dl-horizontal ">
          <dt>Severity:</dt>
          <dd><%= @issue.severity %></dd>
          <dt>Impact:</dt>
          <dd><%= @issue.impact %></dd>
        </dl>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'collapse'%>
<%if can? :update, @issue %>
  <%= link_to 'edit issue', edit_project_issue_path(@project, @issue), class: "btn btn-primary" %>
<% end %>
<div>
	<%= render partial: 'notes/form' %>
	<%= render partial: 'notes/note', collection: @issue.notes %>
</div>