config/routes.rb
LadyBug::Application.routes.draw do

  devise_for :users do
    root to: "devise/sessions#new"
  end

  resources :users do
    match 'add_role' => 'users#add_role', via: :post
    match 'remove_role' => 'users#remove_role', via: :post
  end

  resources :projects do 
    resources :versions
    resources :issues do
      collection do
        match 'search' => 'issues#search', via: [:get, :post], as: :search
      end
      resources :notes
    end   
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base

	resourcify			#rolify

	after_save :create_initial_version

	has_many :issues
	has_many :versions
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true

	private

	def create_initial_version
		v = Version.new
		v.number = "0.0.0" 
		v.project_id = Project.last.id
		v.save
		v.deliver
	end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	authorize_resource 	#cancan
	before_filter :find_project, except: [:index, :new, :create]
	before_filter :define_version, only: [:show, :update, :edit]
	before_filter :authenticate_user!

	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		respond_to do |format|
			if @project.save
				format.html {redirect_to @project, flash: { success: "Project succesfully created."}}
				format.json {head :no_content}
			else
				format.html {render action: 'new'}
				format.json { render json: @project.errors, status: :unprocessable_entity }
			end

		end
	end

	def show
		@search = @project.issues.search(params[:q])
		@project_issues = @project.issues.page(params[:page]).per(25)
		@search.build_condition if @search.conditions.empty?
  		@search.build_sort if @search.sorts.empty?
	end

	def edit
	end

	def update
		respond_to do |format|
		    if @project.update(project_params)
		    	format.html { redirect_to @project, notice: 'project was successfully updated.' }
		        format.json { head :no_content }
		    else
		        format.html { render action: 'edit' }
		        format.json { render json: @project.errors, status: :unprocessable_entity }
		    end
	    end
	end

	def destroy
		@project.versions.destroy_all
		@project.destroy

		flash[:error] = "Project #{@project.name} Deleted!"

		redirect_to projects_path 
	end

	private	
	def project_params
		params.require(:project).permit(:name, :description)
	end

	def find_project
		@project = Project.find(params[:id])
	end

	def define_version
		@version = Version.new
		@version.project_id = @project.id
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
    <%= a.attribute_select%>
  <% end %>
  <%= f.predicate_select only: [:cont, :gt, :lt, :eq]%>
  <%= f.value_fields do |v| %>
    	<%= v.text_field :value %>
  <% end %>
  <%= link_to "remove", '#', class: "remove_fields btn" %>
</div>

app/views/projects/_edit_destroy.html.erb
<% if can? :update, project %>
	<%= link_to 'edit', edit_project_path(project), class: "btn btn-info btn-mini" %>
<%end%>
<% if can? :destroy, project %>
	<%= link_to(project_path(project), method: :delete, data: {confirm: "Really delete the project?"}, class: "btn btn-danger btn-mini") do %>
        <i class="icon-trash icon-white"></i>
    <%end%>
<% end%>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<ul>
  		<% @project.errors.full_messages.each do |error| %>
    		<li><%= error %></li>
  		<% end %>
  	</ul>
    	<%= f.label :name, class: 'strong' %>
    	<%= f.text_field :name, placeholder: "Enter project name", class: "span12" %>
    	<%= f.label :description %>
    	<%= f.text_area :description, placeholder: "Enter project description", class: "span12" ,rows: "9" %>
    	<%= f.submit 'Save', class: "btn btn-primary" %>
      <%= link_to 'Cancel', projects_path, class: "btn" %>
<% end %>

app/views/projects/_project_issues.html.erb
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
        Search issue form:
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse">
    	<div class='offset1'>
		<%= search_form_for @search, url: search_project_issues_path(@project), method: :post do |f| %>
		  <%= f.condition_fields do |c| %>
		    <%= render "projects/condition_fields", f: c %>
		  <% end %>
		  <p><%= link_to_add_fields "Add Conditions", f, :condition %></p>
		  <div class="field">
		    Sort:
		    <%= f.sort_fields do |s| %>
		      <%= s.sort_select %>
		    <% end %>
		  </div>
		  <div class="actions"><%= f.submit "Search", class: 'btn btn-info' %></div>
		<% end %>
  		</div>	
    </div>
  </div>
</div>
<h1> Issue list </h1>
<table class="table table-hover table-striped">
  <thead>
	<TR> 
 		<TH> Issue ID </TH> 
 		<TH> State </TH>
 		<TH> Title </TH> 
 		<TH> Actions </TH>
  </TR>
  </thead>
    <%= paginate @project_issues %>
  	<% @project_issues.each do |issue| %>
  		<TR>
  			<TH> <%= link_to issue.id, project_issue_path(@project,issue) %> </TH>
  			<TH> <span class='<%= state_label(issue.state_name)%>'><%= issue.state_name %></span></TH>
  			<TH> <%= link_to issue.title, project_issue_path(@project,issue) %> </TH>
  			<TH> 
  				<div class="pull-right">
            <%=render 'issues/edit_destroy', project: @project, issue: issue%>
			    </div>
  			</TH>
  		</TR>
  	<%end%>
</table>
<% if can? :create, Issue %>
  <%= link_to "Create a New Issue", new_project_issue_path(@project), class: "btn btn-primary"%>
<% end %>

app/views/projects/edit.html.erb
<legend>Edit Project</legend>

<%= render partial: 'form' %>

<%= link_to(project_path(@project), method: :delete, data: {confirm: "Really delete the project?"}, class: "btn btn-danger btn-mini") do %>
  	<i class="icon-trash icon-white"></i>
<%end%> <br/>
<%= link_to 'Back', projects_path %>

<legend><%=@project.name%>'s versions</legend>
<ul class="inline">
	<%= render partial: 'versions/version', collection: @project.versions %>
</ul>

<%= render partial: 'versions/form' %>

app/views/projects/index.html.erb
<legend>Project list</legend>
<ul class="thumbnails">
  <% @projects.each do |project| %>
    <%if can? :read, project %>
      <li class="span4">
        <div class="thumbnail">
          <h3><%= link_to project.name, project_path(project) %></h3>
          <p class="muted">
            <%= project.description %>
          </p>

          <ul>
            <% project.issues.order(:state).each do |issue| %>
              <li>
                <%= link_to issue.title, project_issue_path(project,issue)%>
                <span class='<%= state_label(issue.state_name)%>'>
                  <%= issue.state_name %>
                </span> 
              </li>
            <%end%>
          </ul>
          <p>
            <%= render 'edit_destroy', project: project %>
            <br />
          </p>
      </li>
    <%end%>
  <%end%>
</ul>
<%if can? :create, Project %>
  <%= link_to "Create a New Project", new_project_path, class: "btn btn-primary"%>
<% end %>

app/views/projects/new.html.erb
<legend>Create e new project</legend>

<%= render partial: 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<legend><%=@project.name%></legend>

<p><%= @project.description %></p>
<%= render 'edit_destroy', project: @project %>
<br />
<br />

<%= render partial: 'projects/project_issues'%>

<%= link_to 'Back', projects_path %>