config/routes.rb
LadyBug::Application.routes.draw do

  devise_for :users do
    root to: "devise/sessions#new"
  end

  resources :users do
    match 'add_role' => 'users#add_role', via: :post
    match 'remove_role' => 'users#remove_role', via: :post
  end

  resources :projects do 
    resources :versions
    resources :issues do
      collection do
        match 'search' => 'issues#search', via: [:get, :post], as: :search
      end
      resources :notes
    end   
  end

  

end

app/models/version.rb
class Version < ActiveRecord::Base

	belongs_to :project

	validates :number, presence: true
	validates_uniqueness_of :number, scope: :project_id

	state_machine :initial => :planned do
		state :planned, value: 0
		state :delivered, value: 2

		event :deliver do
			transition :planned => :delivered
		end


	end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController

	before_filter :authenticate_user!

	def create
  		@version = Version.new(version_params)
  		@version.project_id = params[:project_id]

 		if @version.save
			redirect_to edit_project_path(@version.project_id)
			flash[:success] = "Version Created"
		else
			@project = Project.find(params[:project_id])
			render 'projects/edit'
		end
	end

	def update
		@version = Version.find(params[:id])
		case params[:commit]
		when "change version state" then
			if params[:version][:state_event] == 'deliver'
				@issues_not_closed = all_issue_not_closed
				if @issues_not_closed.empty? and @version.fire_state_event(params[:version][:state_event])
						redirect_to edit_project_path(@version.project), flash: {success: 'Version state updated.'}
				else
					@project = Project.find(params[:project_id])
					flash[:error] = "#{@issues_not_closed.count} issue(s) assigned to version #{@version.number} are not closed"
					render 'projects/edit'
				end
			else
				if @version.fire_state_event(params[:version][:state_event])
					redirect_to edit_project_path(@version.project), flash: {success: 'Version state updated.'}
				end
			end
		else
			@project = Project.find(params[:project_id])
			render 'projects/edit'
		end
	end


	def destroy
		@version = Version.find(params[:id])
		if @version.delivered?
			flash[:error]= "cannot delete delivered versions!"
			@project = Project.find(params[:project_id])
			render 'projects/edit'
		elsif assigned_issues?
			flash[:error]= "cannot delete versions with assigned issues!"
			@project = Project.find(params[:project_id])
			render 'projects/edit'
		else
			@version.destroy

			flash[:error]= "Version Deleted!"

			redirect_to project_path(@version.project)
		end
	end

	private

	def version_params
		params.require(:version).permit(:number)
	end

	def all_issue_not_closed
		issues = Issue.where("project_id = ? and target_version = ?", @version.project_id, @version.id)
		a = issues.map do |issue|
			if not issue.closed?
				issue
			end
		end
	end

	def assigned_issues?
		not Issue.where("project_id = ? and target_version = ?", @version.project_id, @version.id).empty?
	end

end

app/helpers/versions_helper.rb
module VersionsHelper

	def version_label(state)
		case state
			when :planned then "badge badge-success"
			when :delivered then "badge badge-inverse"
		end
	end

end

app/views/versions/_form.html.erb
<h5>Plan a new version:</h5>
<%=  form_for @version, url: project_versions_path(@project) do |f| %>
	<ul>
		<% @version.errors.full_messages.each do |error| %>
		   	<li><span class="text-error"><%= error %></span></li>
		<% end %>
	</ul>
  <p>
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.submit 'Create', class: "btn btn-mini btn-primary"  %>
  </p>
<% end %>

app/views/versions/_version.html.erb
<li>
	<span class='<%= version_label(version.state_name)%>'>
		<%= version.number %>

	<%if version.state_name != :delivered %>
		<%= form_for version, url: project_version_path(@project, version) do |f| %>
			<ul>
		  		<% version.errors.full_messages.each do |error| %>
		    		<li><span class="text-error"><%= error %></span></li>
		  		<% end %>
		  	</ul>
		  	<strong>change state:</strong>
			<%= f.collection_select :state_event, version.state_transitions, :event, :human_to_name %>
			<%= f.submit 'change version state', class: "btn btn-mini" %>
		<% end %>
		<%= link_to(project_version_path(version.project, version), method: :delete, data: {confirm: "Really delete the version?"}, class: "btn btn-danger btn-mini") do %>
  			<i class="icon-trash icon-white"></i>
		<%end%>
	<%end%>
	</span>
</li> 